codei --install-extension aaron-bond.better-comments
codei --install-extension agutierrezr.emmet-keybindings
codei --install-extension apollographql.apollo-midnight-color-theme
codei --install-extension blake-mealey.generate-wt-scheme
codei --install-extension brenix.hacker-theme
codei --install-extension capaj.vscode-standardjs-snippets
codei --install-extension christian-kohler.npm-intellisense
codei --install-extension christian-kohler.path-intellisense
codei --install-extension clintonrost.theme-firefox-devtools
codei --install-extension codezombiech.gitignore
codei --install-extension cweijan.vscode-office
codei --install-extension dbaeumer.vscode-eslint
codei --install-extension eamodio.gitlens
codei --install-extension ecmel.vscode-html-css
codei --install-extension EditorConfig.EditorConfig
codei --install-extension equinusocio.vsc-material-theme-icons
codei --install-extension esbenp.prettier-vscode
codei --install-extension EugeneNor.freezing-moon-theme
codei --install-extension firefox-devtools.vscode-firefox-debug
codei --install-extension foxundermoon.shell-format
codei --install-extension GitHub.remotehub
codei --install-extension Hacker0x01.HackerOne-VS-Code-Theme
codei --install-extension hasiburr.dark-hacker-theme-by-hasibur-r
codei --install-extension hediet.vscode-drawio
codei --install-extension humao.rest-client
codei --install-extension IBM.output-colorizer
codei --install-extension jeff-hykin.better-shellscript-syntax
codei --install-extension karigari.chat
codei --install-extension kevinnorman.kali-terminal-dark
codei --install-extension kisstkondoros.vscode-codemetrics
codei --install-extension leizongmin.node-module-intellisense
codei --install-extension mads-hartmann.bash-ide-vscode
codei --install-extension mikestead.dotenv
codei --install-extension mrmlnc.vscode-scss
codei --install-extension ms-azuretools.vscode-docker
codei --install-extension ms-dotnettools.vscode-dotnet-runtime
codei --install-extension ms-edgedevtools.vscode-edge-devtools
codei --install-extension ms-vscode-remote.remote-wsl
codei --install-extension ms-vscode.powershell
codei --install-extension ms-vscode.remote-repositories
codei --install-extension ms-vscode.vs-keybindings
codei --install-extension ms-vsliveshare.vsliveshare
codei --install-extension ms-vsliveshare.vsliveshare-audio
codei --install-extension msjsdiag.vscode-react-native
codei --install-extension numso.prettier-standard-vscode
codei --install-extension pnp.polacode
codei --install-extension Prisma.prisma
codei --install-extension redhat.vscode-yaml
codei --install-extension Remisa.shellman
codei --install-extension ritwickdey.LiveServer
codei --install-extension rogalmic.bash-debug
codei --install-extension rpinski.shebang-snippets
codei --install-extension shakram02.bash-beautify
codei --install-extension Shan.code-settings-sync
codei --install-extension sibiraj-s.vscode-scss-formatter
codei --install-extension sidthesloth.html5-boilerplate
codei --install-extension skacekachna.win-opacity
codei --install-extension skyapps.fish-vscode
codei --install-extension Stepsize.tech-debt-tracker
codei --install-extension TheNuProjectContributors.vscode-nushell-lang
codei --install-extension timonwong.shellcheck
codei --install-extension Tyriar.windows-terminal
codei --install-extension usernamehw.errorlens
codei --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
codei --install-extension VisualStudioExptTeam.vscodeintellicode
codei --install-extension VisualStudioExptTeam.vscodeintellicode-completions
codei --install-extension VisualStudioExptTeam.vscodeintellicode-insiders
codei --install-extension vscode-icons-team.vscode-icons
codei --install-extension WallabyJs.quokka-vscode
codei --install-extension xabikos.JavaScriptSnippets
codei --install-extension yandeu.five-server
codei --install-extension Zignd.html-css-class-completion
